import React from "react";
import {
  Accordion,
  AccordionItem,
  AccordionItemHeading,
  AccordionItemButton,
  AccordionItemPanel,
} from "react-accessible-accordion";

const FaqContent = [
  {
    title: "How does this work?",
    desc: `Vefes enters into a management contract with the Solar Panel owner to source and manage (including rental and future resale) of solar panels on behalf of Solar Panel owner.`,
    expand: "a",
  },
  {
    title: "Under this arrangement",
    desc: `Vefes on behalf of the Solar Panel owner will procure solar panels from the Solar Plant supplier and rent out these Solar Panels to the Solar Plant producer.
    The Solar Panel owner will receive a variable rental income based on the units generated by these solar panels which will be paid out periodically.
    In case the Solar Panel owner seeks to dispose of these solar panels, Vefes will facilitate the sale.
    `,
    expand: "b",
  },
  {
    title: " What are the income tax benefits of owning solar panels?",
    desc: `During the initial years there is lower tax outgo on account additional tax deduction available for set off against other sources of income (other than salary income) due to higher depreciation (u/s 57 of Income Tax Act, 1961) vis-à-vis income earned on these solar panels during initial years. Consult your tax consultant to ascertain the tax benefits available to you.`,
    expand: "c",
  },
  {
    title: "	How much of the cost of panels recovered in the initial 3 years of operations after considering income tax benefit?",
    desc: `Almost 50% of your cost of panels is recovered in the initial 3 years of operations, which is illustrated here below:`,
    expand: "d",
  },
  {
    title: " How does owning solar panels compare with other options to deploy my funds?",
    desc: `Compared with other options, owning solar panels gives you an opportunity to reduce carbon footprint by generating green energy as well as reducing your tax outgo during the initial years as indicated above.
    `,
    expand: "e",
  },
  {
    title: " What are the benefits of buying these solar panels?",
    desc: `mea case duis tollit et. Etiam nusquam set minium eu sea, ei tale paulo elab. Noluisse mnesarch Et is vero incorrupte eos deserunt quaeren.`,
    expand: "f",
  },
  {
    title: "What are the documents I receive on purchase of solar panels?",
    desc: `On payment of solar panels, you will receive an advance receipt and on delivery of the solar panels to the Solar Plant producer (to whom you have rented the solar panels), you will receive a GST invoice for the same.`,
    expand: "g",
  },
];

const FaqFour = () => {
  return (
    <div
      className="accordion-style-four"
      data-aos="fade-up"
      data-aos-duration="1200"
    >
      <div className="faq-wrraper">
        <Accordion preExpanded={["b"]} allowZeroExpanded>
          {FaqContent.map((item, i) => (
            <AccordionItem className="card" key={i} uuid={item.expand}>
              <AccordionItemHeading className="card-header">
                <AccordionItemButton>
                  <h5 className="mb-0">
                    <button className="btn btn-link">{item.title}</button>{" "}
                  </h5>
                </AccordionItemButton>
              </AccordionItemHeading>
              {/* Accordion Heading */}
              <AccordionItemPanel className="card-body fadeInUp">
                <p>{item.desc}</p>
              </AccordionItemPanel>
              {/* Accordion Body Content */}
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </div>
  );
};

export default FaqFour;
