import React from "react";

const FeatureContent = [
  {
    icon: "Onboarding-pana",
    meta: "Onboarding customer",
    subTitle: `  KYC (Finalise due diligence on required documents & assess your returns).`,
  },
  {
    icon: "House searching-bro",
    meta: "Manage you event",
    subTitle: `Purchase a panel with min 30,000 and own solar assets.`,
  },
  {
    icon: "Accept tasks-rafiki",
    meta: "Start selling ticket",
    subTitle: `Vefes invoices, monitors, manages your purchased solar panels`,
  },
  {
    icon: "Building-cuate",
    meta: "Onboarding customer",
    subTitle: `  Vefes sets up ancillary infrastructure required for sale of power.`,
  },
  {
    icon: "Wallet-pana",
    meta: "Manage you event",
    subTitle: `Monthly income generated by your asset is credited to you.`,
  },
];

const FeatureNine = () => {
  return (
    <div className="row justify-content-center">
      {FeatureContent.map((val, i) => (
        <div
          className="col-lg-4 col-md-6"
          key={i}
          data-aos="fade-up"
          data-aos-duration="1200"
        >
          <div className="block-style-fourteen">
            <div className="illustration">
              <img src={`images/assets/${val.icon}.svg`} alt="icon" />
            </div>
            <div className="title">{val.meta}</div>
            <p className="font-rubik">{val.subTitle}</p>
          </div>
          {/* /.block-style-fourteen */}
        </div>
      ))}
    </div>
    // /.row
  );
};

export default FeatureNine;
