import React from "react";

const FeatureContent = [
  {
    icon: "Onboarding",
    meta: "Get onboard",
    subTitle: `Sign-up with us`,
  },
  {
    icon: "Purchase",
    meta: "Own a solar asset",
    subTitle: `Purchase a panel`,
  },
  
  {
    icon: "Monetize",
    meta: "Monetize your solar asset",
    subTitle: `We rent your panel to Solar Plant for you`,
  },

  {
    icon: "Monitor",
    meta: "Your asset at work",
    subTitle: `We monitor and manage as your panel generates power`,
  },

  {
    icon: "Track",
    meta: "Track your earnings",
    subTitle: `Monthly income generated by your asset is credited to you`,
  },
];

const FeatureNine = () => {
  return (
    <div className="row justify-content-center">
      {FeatureContent.map((val, i) => (
        <div
          className="col-lg-4 col-md-6"
          key={i}
          data-aos="fade-up"
          data-aos-duration="1200"
        >
          <div className="block-style-fourteen">
            <div className="illustration">
              <img src={`images/assets/${val.icon}.svg`} alt="icon" />
            </div>
            <div className="title">{val.meta}</div>
            <p className="font-rubik">{val.subTitle}</p>
          </div>
          {/* /.block-style-fourteen */}
        </div>
      ))}
    </div>
    // /.row
  );
};

export default FeatureNine;
