import React from "react";

const FeatureContent = [
  {
    icon: "Onboarding-pana",
    meta: "Get onboard",
    subTitle: `Sign-up with us and complete your KYC`,
  },
  {
    icon: "House searching-bro",
    meta: "Own a solar asset",
    subTitle: `Purchase a panel with min ₹30,000`,
  },
  {
    icon: "Accept tasks-rafiki",
    meta: "Your asset on work",
    subTitle: `We monitor and manage as your panel generates power`,
  },
  {
    icon: "Building-cuate",
    meta: "",
    subTitle: `We sets up ancillary infrastructure required for sale of power`,
  },
  {
    icon: "Wallet-pana",
    meta: "Track your earnings",
    subTitle: `Monthly income generated by your asset is credited to you`,
  },
];

const FeatureNine = () => {
  return (
    <div className="row justify-content-center">
      {FeatureContent.map((val, i) => (
        <div
          className="col-lg-4 col-md-6"
          key={i}
          data-aos="fade-up"
          data-aos-duration="1200"
        >
          <div className="block-style-fourteen">
            <div className="illustration">
              <img src={`images/assets/${val.icon}.svg`} alt="icon" />
            </div>
            <div className="title">{val.meta}</div>
            <p className="font-rubik">{val.subTitle}</p>
          </div>
          {/* /.block-style-fourteen */}
        </div>
      ))}
    </div>
    // /.row
  );
};

export default FeatureNine;
